# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpaceTimeCube
                                 A QGIS plugin
 This plugin creates a space-time cube based on given data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-26
        copyright            : (C) 2021 by Murat Çalışkan, Berk Anbaroğlu
        email                : caliskan.murat.20@gmail.com, banbar@hacettepe.edu.tr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpaceTimeCube class from file SpaceTimeCube.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .space_time_cube import SpaceTimeCube
    return SpaceTimeCube(iface)
